export const PRODUCT_TYPES = [
  "Suncatcher",
  "Mug",
  "T-shirt",
  "Cap",
  "Ornament",
  "Blanket",
  "Canvas",
  "Acrylic Plaque",
  "Garden Flag",
  "Doormat",
  "Phone Case",
  "Pillow",
  "Poster",
  "Wood Sign",
  "Other",
];

export const BUYER_PERSONAS = [
  "Dog Mom",
  "Cat Mom",
  "Dog Dad",
  "Cat Dad",
  "Dad",
  "Mom",
  "Grandma",
  "Grandpa",
  "Wife",
  "Husband",
  "Couple",
  "Family",
  "Best Friend",
  "Pet Lover",
  "Garden Lover",
  "Beach Lover",
  "Sports Dad",
  "Other",
];

export const OCCASIONS = [
  "Birthday",
  "Pet Memorial",
  "Memorial Gift",
  "Father's Day",
  "Mother's Day",
  "Christmas",
  "Anniversary",
  "Summer",
  "New Home",
  "Retirement",
  "Graduation",
  "Halloween",
  "Thanksgiving",
  "Valentine's Day",
  "Other",
];

export const ART_STYLES = [
  "Watercolor Portrait",
  "Stained Glass",
  "Oil Painting",
  "Vintage Cartoon",
  "Embroidery Style",
  "Line Art",
  "Realistic Portrait",
  "Retro Postcard",
  "Minimal Vector",
  "Pencil Sketch",
  "Christmas Illustration",
  "Summer Illustration",
  "Storybook Illustration",
  "3D Clay Style",
  "Other",
];

export const BRAND_VOICES = [
  "Warm",
  "Friendly",
  "Meaningful",
  "Premium",
  "Simple",
  "Emotional but not cheesy",
  "Fun",
  "Minimal",
  "Gift-focused",
  "US-market natural",
];

export const OUTPUT_REQUESTS = [
  "Product breakdown",
  "Custom fields map",
  "New product angles",
  "Design prompts",
  "Mockup prompts",
  "Shopify title and description",
  "Meta Ads hooks and primary texts",
  "SEO keywords",
  "Export Markdown",
  "Export JSON",
];

export const MOCKUP_SCENES = [
  "Bright American living room window",
  "Clean kitchen counter with morning light",
  "Backyard BBQ summer scene",
  "Beach day lifestyle scene",
  "Christmas tree gift setting",
  "Gift opening on sofa",
  "Pet memorial corner by window",
  "Dad wearing cap outside",
  "Grandma garden table",
  "Cozy bedroom shelf",
  "Modern home office desk",
  "Family picnic scene",
];
