export const PRODUCT_TYPES = [
  "Squishy Acrylic Fridge Magnet",
  "Acrylic Fridge Magnet",
  "Stained Glass Suncatcher",
  "Custom Photo Cap",
  "Personalized Mug",
  "Custom T-Shirt",
  "Personalized Ornament",
  "Personalized Blanket",
  "Custom Canvas Print",
  "Personalized Acrylic Plaque",
  "Personalized Doormat",
  "Garden Flag",
  "Phone Case",
  "Acrylic Keychain",
  "Photo Upload Poster",
  "Personalized Pillow",
  "Other",
];

export const BUYER_PERSONAS = [
  "Dog Mom",
  "Cat Mom",
  "Dog Dad",
  "Cat Dad",
  "Dad",
  "Mom",
  "Grandma",
  "Grandpa",
  "Wife",
  "Husband",
  "Couple",
  "Family",
  "Best Friend",
  "Pet Lover",
  "Garden Lover",
  "Beach Lover",
  "Sports Dad",
  "Other",
];

export const OCCASIONS = [
  "Birthday",
  "Pet Memorial",
  "Memorial Gift",
  "Father's Day",
  "Mother's Day",
  "Christmas",
  "Anniversary",
  "Summer",
  "New Home",
  "Retirement",
  "Graduation",
  "Halloween",
  "Thanksgiving",
  "Valentine's Day",
  "Other",
];

export const ART_STYLES = [
  "Funny Custom Character",
  "Realistic Photo Face + Cartoon Body",
  "Stained Glass",
  "Watercolor Portrait",
  "Oil Painting Portrait",
  "Vintage Cartoon",
  "Embroidery Style",
  "Minimal Line Art",
  "Retro Summer",
  "Christmas Illustration",
  "Premium Lifestyle Mockup",
  "Clean Ecommerce Product Mockup",
  "UGC Phone Photo Style",
  "Other",
];

export const BRAND_VOICES = [
  "Warm",
  "Friendly",
  "Meaningful",
  "Premium",
  "Simple",
  "Emotional but not cheesy",
  "Fun",
  "Minimal",
  "Gift-focused",
  "US-market natural",
];

export const OUTPUT_REQUESTS = [
  "Product breakdown",
  "Opportunity score",
  "Custom fields map",
  "New product angles",
  "Ad content matrix",
  "Component prompts",
  "Design prompts",
  "Mockup prompts",
  "Shopify title and description",
  "Meta Ads hooks and primary texts",
  "SEO keywords",
  "Export Markdown",
  "Export JSON",
];

export const MOCKUP_SCENES = [
  "Bright American living room window",
  "Clean kitchen counter with morning light",
  "Backyard BBQ summer scene",
  "Beach day lifestyle scene",
  "Christmas tree gift setting",
  "Gift opening on sofa",
  "Pet memorial corner by window",
  "Dad wearing cap outside",
  "Grandma garden table",
  "Cozy bedroom shelf",
  "Modern home office desk",
  "Family picnic scene",
];
